### PR TITLE
Blog

### PR DESCRIPTION
**Pull request by carlosgauci**
@TuanaCelik @bilgeyucel here's the first draft of the blog. I've left the placeholder/test posts there for now.

[Blog listing page](https://haystack-home-git-blog-deepset-overnice.vercel.app/blog) - the newest post is larger at the top and it's paginated at 10 posts (9 on the frontpage), this can be changed from config.toml

[Blog post](https://haystack-home-git-blog-deepset-overnice.vercel.app/blog/post-18) - the body here is the same as the tutorial posts so anything that works there will work here like codeblocks etc. The content is a bit wide for a blog post since there's no right sidebar, we should probably make it narrower to be more readable?

[Author page](https://haystack-home-git-blog-deepset-overnice.vercel.app/blog/authors/jane-doe) - used the same hero as the tutorials/blog here, not sure if it looks good, lmk what you think and we can change it if not.

### CODE REVIEW

**Review by TuanaCelik — COMMENTED** [review]
Hey @carlosgauci - this all looks good to me, I have a couple of questions:
- would it be possible to make the social logos on the blog post itself next to the author names too? I the Haystack purple?
image
- Could we make the social logos on the author pages white? Just for the aesthethic? :)
- Also, a question we had from our side: Do you have best practice recommendations for handing assets per author and blog? Should we create a folder in static/images/blog-name ? And add all the images for a given blog there? Any comments on how to best maintain those?

**Comment by carlosgauci** [comment]
> 

Hey @TuanaCelik, 

I've added white and dark versions of the social icons, and added social links to the blog posts. In case you wanted to try some different colors, you can edit the SVGs and change the "fill" property to change the color.

For the images, it's mostly personal preference, you can either use one static folder or split them up as you said. Putting them in the same folder is probably easier if you plan to reuse a lot of images between posts, else if you prefer to be more organized you can split them.
I was also trying to implement the option of putting them in a folder with the blog post, so instead of /blog/post-slug.md, you would have /blog/post-slug/index.md, and put all the images for that post inside the /post-slug/ directory. For some reason the image paths aren't correct when deployed, only locally, so I'm still trying to solve that.

**Comment by TuanaCelik** [comment]
Hey @carlosgauci - I quite like the folder solution that you have for post19 indeed. 
We would rarely ever share images across posts so that's also ok. 
A few questions: even though the post would be in post_name/index.md it looks like the URLs for the post would still be /blog/post_name correct? 
And for each image, we would use test
I hope I've got that right. Let me know. @bilgeyucel @masci wdyt about this way of organizing the posts and images?

**Comment by carlosgauci** [comment]
Hey @TuanaCelik, yep you're correct about the urls.
The images should be working without specifying the post slug since they're in the same directory, so `test`. it's working locally but not when deployed, because we have trailing slashes disabled through vercel.json. Haven't found a way to enable them for a specific directory, and enabling them site-wide will change old URLs to include a trailing slash so it might affect seo.

**Comment by masci** [comment]
@TuanaCelik I like the idea of organising images under each post. I understand the tradeoff but on my personal website I have all the images in one folder an it's a mess (too late and too lazy to go back) and I would gladly have a few duplicated images in case we need to use the same across multiple posts (very unlikely anyways).

**Review by bilgeyucel — APPROVED** [review]

**Pull request merged**
