### PR TITLE
Attempting fix for twitter cards

### LINKED ISSUE #44: Twitter meta image
When sharing the webpage on twitter, the meta image does not show up. This probably requires a fix in the config file
image

### PR DESCRIPTION
**Pull request by TuanaCelik**
Attempts to fix #44

### CODE REVIEW

**Comment by TuanaCelik** [comment]
I'm not sure this worked :D

**Review by carlosgauci — APPROVED** [review]
Looks good, seems to have worked on the preview :)

**Comment by bilgeyucel** [comment]
Do we need to update the `og:image` as well?

**Comment by TuanaCelik** [comment]
No the of image is fine, it can handle relative paths. But turns out Twitter requires absolute 🤦🏽‍♀️

Let's try this.. if not we can do other minor fixes :)

**Pull request merged**
