### PR TITLE
fix copy buttons, email filter

### PR DESCRIPTION
**Pull request by carlosgauci**
- Fixed copy buttons from breaking when no language is specified
- Modified newsletter email filter to allow "+"

### CODE REVIEW

**Comment by TuanaCelik** [comment]
Many thanks @carlosgauci - LGTM 🙌🏽

**Review by TuanaCelik — COMMENTED** [review]
Thanks @carlosgauci - It works now. There's a scenario where it doesn't though. If the email already has a '.' (like our work emails 😄 )
e.g.: bilge.yucel+test1@deepse.ai]

Apart from that all good. Will merge asap

**Comment by carlosgauci** [comment]
> Thanks @carlosgauci - It works now. There's a scenario where it doesn't though. If the email already has a '.' (like our work emails 😄 ) e.g.: [bilge.yucel+test1@deepse.ai](mailto:bilge.yucel+test1@deepse.ai)]
> 
> Apart from that all good. Will merge asap

Sorry about that, should work now :)

**Review by bilgeyucel — APPROVED** [review]
Nice, thank you 💯

**Review by TuanaCelik — APPROVED** [review]

**Pull request merged**
